server:
  port: 28080
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/henry_site?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: root
        #使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20
    freemarker:
      allow-request-override: false  #缓存配置
      enabled: true
      cache: false  #缓存配置
      check-template-location: true  
      charset: UTF-8  #编码格式
      content-type: text/html; charset=utf-8
      request-context-attribute: req  #req访问request
      expose-request-attributes: false  
      expose-session-attributes: false  
      expose-spring-macro-helpers: false  
      suffix: .ftl  
      template-loader-path: classpath:/templates  
      settings:
        number_format: '0.##'   #数字格式化，无小数点
        template_update_delay : 0
        default_encoding : UTF-8
    aop:
      auto: true
      proxy-target-class: true
    servlet:
          multipart:
            max-file-size: 10Mb
            max-request-size: 100Mb
#mybatis
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-aliases-package: com.tofba.model
mapper:
  mappers: com.tofba.dao
  not-empty: false
  identity: MYSQL
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
logging:
  level:
    com.tofba.dao : DEBUG
swagger:
  show: true